### ISSUE TITLE
UnsatisfiedLinkError for native example

### ISSUE THREAD

**Issue by cansik** [yoctopuce/yoctolib_java#1]
I tried to connect to my usb temperature sensor over the native interface you provide. The library is linked correctly, but I get an unsatisfied link error.

I have a MacOS Sierra (10.12.1 (16B2555)).

Here is the code I use (your example):

```java
try {

    // sets up the API to use direct USB access
    YAPI.RegisterHub("usb");

    System.out.println("Device connected by USB");
    YModule module = YModule.FirstModule();
    while (module != null) {
        System.out.println(module.get_serialNumber());
        module = module.nextModule();
    }
    YAPI.FreeAPI();

} catch (YAPI_Exception ex) {
    System.out.println("error:" + ex.getLocalizedMessage());
    System.exit(1);
}
```

And here the error message:

```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.yoctopuce.YoctoAPI.YJniWrapper.reserveUSBAccess()V
	at com.yoctopuce.YoctoAPI.YJniWrapper.reserveUSBAccess(Native Method)
	at com.yoctopuce.YoctoAPI.YUSBHub.<init>(YUSBHub.java:91)
	at com.yoctopuce.YoctoAPI.YAPIContext._AddNewHub(YAPIContext.java:587)
	at com.yoctopuce.YoctoAPI.YAPIContext.RegisterHub(YAPIContext.java:796)
	at com.yoctopuce.YoctoAPI.YAPI.RegisterHub(YAPI.java:323)
	at ch.bildspur.yocto.Main.listDevices(Main.java:22)
	at ch.bildspur.yocto.Main.main(Main.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Am I missing something?

**Comment by cansik** [comment]
Is the method missing in your library?

``` bash
nm -gU libyapi.dylib | grep reserveUSBAccess
```

returned nothing. With `USB` I just get following methods:

``` bash
nm -gU libyapi.dylib | grep USB

00000000000239c0 T _yHashUrlUSB
00000000000172a0 T _yUSBGetBooloader
0000000000010150 T _yUSBReleaseAllDevices
0000000000010730 T _yUSBUpdateDeviceList
000000000000f6f0 T _ypUpdateUSB
0000000000036440 T _yyyUSBGetInterfaces
0000000000035d10 T _yyyUSB_init
00000000000362d0 T _yyyUSB_stop
```

**Comment by yoctopuce** [comment]
It seems that our release script has not copied the right `libyapi.dylib` file. We are fixing this issue right now, and a new library should be available tomorrow. Until then you can use this file: http://www.yoctopuce.com/tmp/libyapi.zip

**Comment by cansik** [comment]
Yep now it's working! Thank you for the fast answer! 👍
